### ISSUE TITLE
How to get the series name and episode number?

### ISSUE THREAD

**Issue by Vorffeed** [stefanodvx/crunpyroll#24]
Could someone could give me a hand to get the name of the series and the number of the specific episode when you enter the episode code ie GVWU07MPE, the script has been passed to me and I do not have much idea of python programming and I have been able to modify it to my needs as best I could, asking you by keyboard to enter the episode code and inserting it, but as much as I look at the document with the info crunpyrol I do not clarify how I should make calls to get that information.
That is to say that when I enter "GVWU07MPE" it should show me this Wind Breaker - 01
```

episoide_id = input("Insert episode code: ")


async def main():
	await client.start()
	index = await client.get_index()
	# Get streams of the episode/movie

	streams = await client.get_streams(episode_id)
	
	# Get manifest of the format you prefer
	manifest = await client.get_manifest(streams.url)
	
	access_token = client.session.access_token
	print(access_token)
.
.
.
asyncio.run(main())

```

**Comment by Vorffeed** [comment]
to do what you say it would be like this? 
`episode = await client.get_episodes(episode_id)`
as I said I don't understand much about making calls in python.

**Comment by inks007** [comment]
The client.get_episodes() method doesn't exist. I implemented it as client.get_objects(media_id), but the PR hasn't been reviewed yet.

If you want to try it, you will have to use my [branch](https://github.com/inks007/crunpyroll/tree/bleeding-edge) at the moment. If you are using pip, then `pip uninstall crunpyroll` followed by `pip install https://github.com/inks007/crunpyroll/archive/bleeding-edge.zip` should do the trick.

**Comment by Vorffeed** [comment]
I get this error, what do I do wrong? T_T


`episode = await client.get_objects(media_id)`

```
Traceback (most recent call last):
  File "E:\Crunchy Videos\Temporales\crunpyroll_cr2.py", line 101, in <module>
    asyncio.run(main())
  File "C:\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\Crunchy Videos\Temporales\crunpyroll_cr2.py", line 46, in main
    episode = await client.get_objects(media_id)
                                       ^^^^^^^^
NameError: name 'media_id' is not defined
```

**Comment by Vorffeed** [comment]
I finally got it through yp-dlp what I needed, saving me several functions that I had
