### ISSUE TITLE
get_old_streams seems to have been retired

### ISSUE THREAD

**Issue by orbitalflower** [stefanodvx/crunpyroll#33]
The API function for `get_old_streams` now returns a 403. The yt-dlp project recently reported that Crunchyroll has closed the last non-DRM endpoint, so that might have something to do with it.

**Comment by stefanodvx** [comment]
Yea, looks like it is dead. Well, I knew that it would have been deprecated, that's why I put the alert. Everyone should use their CDM and the proper endpoint for that!
